### PR TITLE
General update

### PR DESCRIPTION
**Pull request by gep13**
I have been going through a process of updating some addins, based on information that @jericho has been collecting in his audit report:

https://github.com/cake-contrib/Home

As a result, I have done a brief update of files in this repository.

@MihaMarkic do you have any objections to any of these?  Basically this is an attempt to bring some consistency across the repositories, to help with the longer term maintenance effort.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by MihaMarkic** [comment]
@gep13 Looks fine to me. Heck, if somethings go wrong with build process you'll be first to know anyway :)

**Comment by gep13** [comment]
>@MihaMarkic said...
Heck, if somethings go wrong with build process you'll be first to know anyway :)

Ha ha, always happy to help!

Any objections to me working my way through my list of your addins to update them in a similar way?

**Comment by gep13** [comment]
@MihaMarkic well, that failed build error on the merge to master is an interesting one.

I know exactly what is going on, and I can submit a change to fix it, but interesting that it is coming up now?!?

**Comment by gep13** [comment]
@MihaMarkic that is the build working again 😄

**Comment by MihaMarkic** [comment]
> Any objections to me working my way through my list of your addins to update them in a similar way?

No objections at all, go ahead, appreciated.

**Pull request merged**
